# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI Tests
env:
  DAY_OF_WEEK: Monday
  
on:
  push:
  pull_request:

jobs:
  test-ci:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        node-version: ${{ matrix.node-version }}
        message: |
            Hello world ! :wave:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: yarn install --frozen-lockfile
    - run: yarn test
