# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Tests
env:
  DAY_OF_WEEK: Monday
  
on:
  push:
  pull_request:

jobs:
  test-ci:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/first-interaction@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        node-version: ${{ matrix.node-version }}
        issue-message: '# Message with markdown.\nThis is the message that will be displayed on users'
        pr-message: 'Message that will be displayed on users'
    - run: yarn install --frozen-lockfile
    - run: yarn test
    
#     - name: 💬 Send Message to Slack 🚀
#       uses: archive/github-actions-slack@v2.4.0
